load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "day12",
    srcs = ["day12.go"],
    data = [":input.txt"]
)

go_binary(
    name = "part2",
    srcs = ["part2.go"],
    data = [":input.txt"]
)